python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 5 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/5/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 8 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/8/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 9 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/9/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 12 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/12/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 17 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/17/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 18 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/18/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 20 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/20/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 22 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/22/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 23 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/23/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 24 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/24/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 27 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/27/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 28 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/28/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 29 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/29/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 30 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/30/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 31 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/31/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 33 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/33/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 34 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/34/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 37 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/37/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 38 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/38/tmp/ranking
python ranking/RankNet.py --lr 0.001 --debug --standardize --data_fold 39 --output /devdata3/zjy/L2RTCP/code/data/cross_data_py/39/tmp/ranking